# Generated by Django 5.0.6 on 2024-06-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_usertoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlog',
            name='computer_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='event_category',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='event_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='event_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='source_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='time_generated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
